### PR TITLE
Update device component

### PR DESCRIPTION
**Pull request by jo-jstrm**
Created a MUI Grid and added a button. Two-row design as in Figma is a problem currently, therefore we have a one-row design for now. [SO-Question](https://stackoverflow.com/questions/73208091/align-react-material-ui-grid-with-different-number-of-rows-per-column)

Would still like to merge.

### CODE REVIEW

**Comment by TB-DevAcc** [comment]
I need a little bit more time to review this and check the SO question. Running this currently still throws an "Invalid dependencies have been reported" that is grpc related, are any dependencies missing?

**Review by TB-DevAcc — CHANGES_REQUESTED** [review]
PR to fix device list is now online at #29.

**Comment by TB-DevAcc** [comment]
@jo-jstrm Why is this closed? It should be merged into dev now imo.

**Comment by jo-jstrm** [comment]
I thought your other PR made this irrelevant =O

**Review by TB-DevAcc — APPROVED** [review]
👍

**Pull request merged**
